
export const logos  = [
    {
        name:"PostgreSQL",
        background:'#336791',
        logo:"http://localhost:8080/img/postgresql.png",
        color:"white"
    },
    {
        name:"Mongodb",
        background:'black',
        logo:"http://localhost:8080/img/mongodb.png",
        color:"white"
    },
    {
        name:"AWS",
        background:'black',
        logo:"http://localhost:8080/img/aws.png",
        color:"white"

    },
    {
        name:"React",
        background:'#61DAFB',
        logo:"http://localhost:8080/img/react.png",
        color:"black"
    },
    {
        name:"Java Script",
        background:'#F7DF1C',
        logo:"http://localhost:8080/img/js.png",
        color:"black"
    },
    {
        name:"TypeScript",
        background:'#3078C6',
        logo:"http://localhost:8080/img/typescript.png",
        color:"white"
    },
    {
        name:"Express",
        background:'black',
        logo:"http://localhost:8080/img/express-s.png",
        color:"white"
    },
    {
        name:"Git",
        background:'#F05032',
        logo:"http://localhost:8080/img/git.png",
        color:"white"
    },
    {
        name:"Node JS",
        background:'#349934',
        logo:"http://localhost:8080/img/nodejs.png",
        color:"white"
    },
    {
        name:"Tailwind",
        background:'#38B2AC',
        logo:"http://localhost:8080/img/tailwind.png",
        color:"white"
    },
]